"""empty message

Revision ID: 649f32ca0e8e
Revises: f4c15152deb0
Create Date: 2022-07-07 22:36:32.760398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649f32ca0e8e'
down_revision = 'f4c15152deb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_from', sa.String(length=120), nullable=False),
    sa.Column('server_to', sa.String(length=120), nullable=False),
    sa.Column('gold_trade', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'username')
    op.drop_table('product')
    # ### end Alembic commands ###
